# Generated by Django 2.1.1 on 2020-03-09 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='first_name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 4, 16, 384430, tzinfo=utc), verbose_name='created_at')),
                ('last_connexion', models.DateTimeField(null=True, verbose_name='last_connexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('is_modarator', models.BooleanField(default=False, verbose_name='is_modarator')),
                ('avatar', models.ImageField(upload_to='avatar/')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='movie_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.IntegerField()),
                ('title_movie', models.CharField(max_length=250, verbose_name='titre')),
                ('link_download', models.URLField(verbose_name='lien_telechargement')),
                ('voice_language', models.CharField(choices=[('FR', 'FRANÇAIS'), ('EN', 'ANGLAIS'), ('JP', 'JAPONAIS'), ('...', 'AUTRE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='langue')),
                ('quality_video', models.CharField(choices=[('GD', 'BONNE'), ('PASS', 'MOYENNE'), ('BAD', 'MAUVAISE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='qualite_video')),
                ('quality_audio', models.CharField(choices=[('GD', 'BONNE'), ('PASS', 'MOYENNE'), ('BAD', 'MAUVAISE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='qualite_audio')),
                ('subtitle', models.CharField(choices=[('Y', 'OUI'), ('N', 'NON')], max_length=3, verbose_name='est_soustitre')),
                ('subtitle_language', models.CharField(choices=[('FR', 'FRANÇAIS'), ('EN', 'ANGLAIS'), ('JP', 'JAPONAIS'), ('...', 'AUTRE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='langue_du_soustitre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 4, 16, 404417, tzinfo=utc), verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 4, 16, 404417, tzinfo=utc), verbose_name='updated_at')),
                ('member', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcu.member')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['title_movie'],
            },
        ),
        migrations.CreateModel(
            name='tv_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tv', models.IntegerField()),
                ('nb_season', models.IntegerField(default=1, verbose_name='saison')),
                ('nb_episode', models.IntegerField(default=1, verbose_name='episode')),
                ('title_tv', models.CharField(max_length=250, verbose_name='titre')),
                ('link_download', models.URLField(verbose_name='lien_telechargement')),
                ('voice_language', models.CharField(choices=[('FR', 'FRANÇAIS'), ('EN', 'ANGLAIS'), ('JP', 'JAPONAIS'), ('...', 'AUTRE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='langue')),
                ('quality_video', models.CharField(choices=[('GD', 'BONNE'), ('PASS', 'MOYENNE'), ('BAD', 'MAUVAISE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='qualite_video')),
                ('quality_audio', models.CharField(choices=[('GD', 'BONNE'), ('PASS', 'MOYENNE'), ('BAD', 'MAUVAISE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='qualite_audio')),
                ('subtitle', models.CharField(choices=[('Y', 'OUI'), ('N', 'NON')], max_length=3, verbose_name='est_soustitre')),
                ('subtitle_language', models.CharField(choices=[('FR', 'FRANÇAIS'), ('EN', 'ANGLAIS'), ('JP', 'JAPONAIS'), ('...', 'AUTRE'), ('N/A', 'AUCUN')], max_length=10, verbose_name='langue_du_soustitre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 4, 16, 407414, tzinfo=utc), verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 4, 16, 407414, tzinfo=utc), verbose_name='updated_at')),
                ('member', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcu.member')),
            ],
            options={
                'verbose_name': 'serie_anime',
                'verbose_name_plural': 'series_animes',
                'ordering': ['title_tv'],
            },
        ),
    ]
