# Generated by Django 2.1.1 on 2020-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lcu', '0002_auto_20200311_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sender', models.CharField(max_length=150, verbose_name='name_sender')),
                ('message', models.CharField(max_length=250, verbose_name='message')),
                ('email_sender', models.EmailField(max_length=250, null=True, verbose_name='email_sender')),
                ('id_movie', models.IntegerField(null=True)),
                ('id_tv', models.IntegerField(null=True)),
                ('is_reply', models.BooleanField(default=False, verbose_name='is_reply')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('is_locked', models.BooleanField(default=False, verbose_name='is_locked')),
                ('recieve_mail', models.BooleanField(default=False, verbose_name='recieve_mail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['name_sender'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='is_locked',
            field=models.BooleanField(default=False, null=True, verbose_name='is_locked'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcu.member'),
        ),
    ]
