# Generated by Django 2.1.1 on 2019-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAndMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movie', models.IntegerField()),
                ('title_movie', models.CharField(max_length=250)),
                ('link_telegram', models.URLField()),
                ('voice_language', models.CharField(choices=[('FR', 'FRENCH'), ('EN', 'ENGLISH'), ('JP', 'JAPANESE'), ('..', 'NOTHING')], max_length=2)),
                ('quality_video', models.CharField(choices=[('G', 'GOOD'), ('M', 'MEDUIM'), ('B', 'BAD'), ('.', 'NOTHING')], max_length=1)),
                ('quality_audio', models.CharField(choices=[('G', 'GOOD'), ('M', 'MEDUIM'), ('B', 'BAD'), ('.', 'NOTHING')], max_length=1)),
                ('subtitle', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('subtitle_language', models.CharField(choices=[('FR', 'FRENCH'), ('EN', 'ENGLISH'), ('JP', 'JAPANESE'), ('..', 'NOTHING')], max_length=2)),
            ],
            options={
                'verbose_name': 'movie_detail',
                'ordering': ['title_movie'],
            },
        ),
        migrations.DeleteModel(
            name='movies_details',
        ),
    ]
