# Generated by Django 2.1.1 on 2019-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAndMe', '0002_auto_20190614_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='tv_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_episode', models.IntegerField()),
                ('title_tv', models.CharField(max_length=250)),
                ('link_telegram', models.URLField()),
                ('voice_language', models.CharField(choices=[('FRANÇAIS', 'FRANÇAIS'), ('ANGLAIS', 'ANGLAIS'), ('JAPONAIS', 'JAPONAIS'), ('AUCUN', 'AUCUN')], max_length=10)),
                ('quality_video', models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUNCUN', 'AUNCUN')], max_length=10)),
                ('quality_audio', models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUNCUN', 'AUNCUN')], max_length=10)),
                ('subtitle', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3)),
                ('subtitle_language', models.CharField(choices=[('FRANÇAIS', 'FRANÇAIS'), ('ANGLAIS', 'ANGLAIS'), ('JAPONAIS', 'JAPONAIS'), ('AUCUN', 'AUCUN')], max_length=10)),
            ],
            options={
                'verbose_name': 'tv_detail',
                'ordering': ['title_tv'],
            },
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='quality_audio',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUNCUN', 'AUNCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='quality_video',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUNCUN', 'AUNCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='subtitle',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=3),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='subtitle_language',
            field=models.CharField(choices=[('FRANÇAIS', 'FRANÇAIS'), ('ANGLAIS', 'ANGLAIS'), ('JAPONAIS', 'JAPONAIS'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='voice_language',
            field=models.CharField(choices=[('FRANÇAIS', 'FRANÇAIS'), ('ANGLAIS', 'ANGLAIS'), ('JAPONAIS', 'JAPONAIS'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
    ]
