# Generated by Django 2.1.1 on 2019-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesAndMe', '0003_auto_20190614_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_detail',
            old_name='id_episode',
            new_name='id_tv',
        ),
        migrations.AddField(
            model_name='tv_detail',
            name='nb_episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tv_detail',
            name='nb_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='quality_audio',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='quality_video',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tv_detail',
            name='quality_audio',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tv_detail',
            name='quality_video',
            field=models.CharField(choices=[('BONNE', 'BONNE'), ('MOYENNE', 'MOYENNE'), ('MAUVAISE', 'MAUVAISE'), ('AUCUN', 'AUCUN')], max_length=10),
        ),
    ]
