# Generated by Django 2.1.1 on 2020-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BhAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='BhUser',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('whatsapp_phone', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('profile_picture', models.URLField()),
                ('date_of_birth', models.DateField(max_length=250)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='beakhub.BhAccount')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
