# Generated by Django 2.1.1 on 2020-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0003_auto_20201017_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhuser',
            name='date_of_birth',
            field=models.DateField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bhuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bhuser',
            name='profile_picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bhuser',
            name='whatsapp_phone',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
