# Generated by Django 2.1.1 on 2020-10-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0004_auto_20201017_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='photo_user/'),
        ),
    ]
