# Generated by Django 2.1.1 on 2020-11-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0005_auto_20201026_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaddress',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beakhub.BhJob'),
            preserve_default=False,
        ),
    ]
