# Generated by Django 2.1.1 on 2020-11-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0007_auto_20201101_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
