# Generated by Django 2.1.1 on 2020-11-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0009_bhcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhUserLikeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beakhub.BhJob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beakhub.BhUser')),
            ],
            options={
                'verbose_name': 'Aime',
                'verbose_name_plural': 'Aiment',
                'ordering': ['created_at'],
            },
        ),
    ]
