# Generated by Django 2.1.1 on 2020-12-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beakhub', '0010_bhuserlikejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COMMENT', 'COMMENT'), ('LIKE', 'LIKE'), ('VIEW', 'VIEW')], max_length=25, verbose_name='ACTION')),
                ('is_view', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beakhub.BhJob')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='beakhub.BhUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='beakhub.BhUser')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['created_at'],
            },
        ),
    ]
